add dts support for pistachio_marduk
CreatorDev/linux-old pull request #12
Opened 2016-11-25 05:19 UTC by abhimanyuv1

This currently enable initial dts checkin. Also add nand boot and audio support

2016-12-06 12:00 UTC, Avinash95 commented
verified

2016-12-06 13:03 UTC, francois-berder-imgtec commented
The only issue now is that the dts is missing the wifi alias.

2016-12-06 13:16 UTC, abhijit-mahajani-imgtec requested changes
I think pistachio.dtsi is also missing the change
https://github.com/CreatorDev/openwrt/blob/ci40/target/linux/pistachio/patches-4.1/0062-pistachio.dtsi-add-usb_pwr_on_pins-in-pinctrl.patch

This was required to fix adapter support for Ci40. i.e. booting from USB/Adapter please refer internal ticket https://issues.ba.imgtec.org/browse/KIN-805

2016-12-06 13:28 UTC, abhijit-mahajani-imgtec requested changes
pistachio_marduk.dts is missing the change for usb_phy support
https://github.com/CreatorDev/openwrt/blob/ci40/target/linux/pistachio/patches-4.1/0063-marduk_dts-enable-vbus-drive-for-usb_phy.patch

2016-12-06 13:37 UTC, abhijit-mahajani-imgtec commented on arch/mips/boot/dts/img/pistachio_marduk.dts
>  	};
Its missing this commit https://github.com/CreatorDev/openwrt/blob/ci40/target/linux/pistachio/patches-4.1/0097-dts-set-linux-mtd-name-for-flash-devices.patch

2016-12-07 05:32 UTC, abhijit-mahajani-imgtec commented
> The only issue now is that the dts is missing the wifi alias.

Since this PR is just about basic platform support (not including WiFi), i think it should be ok. WiFi alias and all uccp related changes can be added in subsequent PR.

2016-12-13 12:06 UTC, abhimanyuv1 commented
Wifi is not included as i didnt had way to test with buildroot without adding uccp module package in it. I will do it in next creator time (i am fine if anyone else want to do it) 

>pistachio_marduk.dts is missing the change for usb_phy support
usb_phy changes are included in uboot so i expect that once ubus power is on in uboot, it will be on in kernel too. I would need to verify it though. if someone can verify it easily then let me know if it is failing.

2016-12-14 11:32 UTC, abhijit-mahajani-imgtec approved these changes

2017-01-02 05:20 UTC, merged